### ISSUE TITLE
Keycloak is not discoverable by Prometheus

### ISSUE THREAD

**Issue by aidenkeating** [aerogearcatalog/keycloak-apb#21]
Currently the Keycloak metrics are not discoverable by Prometheus. This is because the Keycloak service does not contain the `org.aerogear.metrics/ssl_endpoint` annotation pointing at the Keycloak metrics endpoint.

This annotation should be added so that when Prometheus is provisioned alongside Keycloak the metrics are discoverable.

@ciaranRoche Would you mind taking a look?

**Comment by ciaranRoche** [comment]
@aidenkeating no problem :+1:
