### ISSUE TITLE
keycloak apb should create a configmap with the public info and secret with the private info

### ISSUE THREAD

**Issue by maleck13** [aerogearcatalog/keycloak-apb#31]
As per the proposal https://github.com/aerogear/proposals/blob/master/apbs/create-secret-and-configmap-during-provision.md

Keycloak should create a configmap with the public information (IE information it wants to expose as config to the client) and a secret with the private information (IE login username passwords etc everything that it does not want to expose).

**Comment by maleck13** [comment]
@matzew ping if you want me to create a follow on Jira let me know

**Comment by matzew** [comment]
yeah, that would be nice, having a JIRA 

I think we can get that fix in quickly :)

**Comment by maleck13** [comment]
This looks to be done now @pb82
